language: generic 
sudo: required

services:
  - docker
  
before_install:
  - docker build -t k3snoob/docker-react1 -f Dockerfile.dev .
  
script:
  - docker run -e CI=true k3snoob/docker-react1 npm run test