version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/app'
      - '/app/node_modules'
  tests:
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: ["npm", "run", "test"]